package com.snow.phoenix.blog.app.core.model.phoenix_blog;

import java.util.Date;

public class BlogComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..blog_comment.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..blog_comment.commenter_id
     *
     * @mbggenerated
     */
    private Integer commenterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..blog_comment.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..blog_comment.commentee_id
     *
     * @mbggenerated
     */
    private Integer commenteeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..blog_comment.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..blog_comment.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..blog_comment.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..blog_comment.id
     *
     * @return the value of phoenix_blog..blog_comment.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..blog_comment.id
     *
     * @param id the value for phoenix_blog..blog_comment.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..blog_comment.commenter_id
     *
     * @return the value of phoenix_blog..blog_comment.commenter_id
     *
     * @mbggenerated
     */
    public Integer getCommenterId() {
        return commenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..blog_comment.commenter_id
     *
     * @param commenterId the value for phoenix_blog..blog_comment.commenter_id
     *
     * @mbggenerated
     */
    public void setCommenterId(Integer commenterId) {
        this.commenterId = commenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..blog_comment.content
     *
     * @return the value of phoenix_blog..blog_comment.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..blog_comment.content
     *
     * @param content the value for phoenix_blog..blog_comment.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..blog_comment.commentee_id
     *
     * @return the value of phoenix_blog..blog_comment.commentee_id
     *
     * @mbggenerated
     */
    public Integer getCommenteeId() {
        return commenteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..blog_comment.commentee_id
     *
     * @param commenteeId the value for phoenix_blog..blog_comment.commentee_id
     *
     * @mbggenerated
     */
    public void setCommenteeId(Integer commenteeId) {
        this.commenteeId = commenteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..blog_comment.create_time
     *
     * @return the value of phoenix_blog..blog_comment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..blog_comment.create_time
     *
     * @param createTime the value for phoenix_blog..blog_comment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..blog_comment.deleted
     *
     * @return the value of phoenix_blog..blog_comment.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..blog_comment.deleted
     *
     * @param deleted the value for phoenix_blog..blog_comment.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..blog_comment.update_time
     *
     * @return the value of phoenix_blog..blog_comment.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..blog_comment.update_time
     *
     * @param updateTime the value for phoenix_blog..blog_comment.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}