package com.snow.phoenix.blog.app.core.model.phoenix_blog;

import java.util.Date;

public class Live {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..live.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..live.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..live.img
     *
     * @mbggenerated
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..live.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..live.introduce
     *
     * @mbggenerated
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..live.ocntent
     *
     * @mbggenerated
     */
    private String ocntent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..live.read_sum
     *
     * @mbggenerated
     */
    private Integer readSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..live.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..live.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..live.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..live.id
     *
     * @return the value of phoenix_blog..live.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..live.id
     *
     * @param id the value for phoenix_blog..live.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..live.user_id
     *
     * @return the value of phoenix_blog..live.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..live.user_id
     *
     * @param userId the value for phoenix_blog..live.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..live.img
     *
     * @return the value of phoenix_blog..live.img
     *
     * @mbggenerated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..live.img
     *
     * @param img the value for phoenix_blog..live.img
     *
     * @mbggenerated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..live.title
     *
     * @return the value of phoenix_blog..live.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..live.title
     *
     * @param title the value for phoenix_blog..live.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..live.introduce
     *
     * @return the value of phoenix_blog..live.introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..live.introduce
     *
     * @param introduce the value for phoenix_blog..live.introduce
     *
     * @mbggenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..live.ocntent
     *
     * @return the value of phoenix_blog..live.ocntent
     *
     * @mbggenerated
     */
    public String getOcntent() {
        return ocntent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..live.ocntent
     *
     * @param ocntent the value for phoenix_blog..live.ocntent
     *
     * @mbggenerated
     */
    public void setOcntent(String ocntent) {
        this.ocntent = ocntent == null ? null : ocntent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..live.read_sum
     *
     * @return the value of phoenix_blog..live.read_sum
     *
     * @mbggenerated
     */
    public Integer getReadSum() {
        return readSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..live.read_sum
     *
     * @param readSum the value for phoenix_blog..live.read_sum
     *
     * @mbggenerated
     */
    public void setReadSum(Integer readSum) {
        this.readSum = readSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..live.create_time
     *
     * @return the value of phoenix_blog..live.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..live.create_time
     *
     * @param createTime the value for phoenix_blog..live.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..live.deleted
     *
     * @return the value of phoenix_blog..live.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..live.deleted
     *
     * @param deleted the value for phoenix_blog..live.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..live.update_time
     *
     * @return the value of phoenix_blog..live.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..live.update_time
     *
     * @param updateTime the value for phoenix_blog..live.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}