package com.snow.phoenix.blog.app.core.model.phoenix_blog;

import java.util.Date;

public class MessageBoard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..message_board.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..message_board.messager_id
     *
     * @mbggenerated
     */
    private Integer messagerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..message_board.messagee_id
     *
     * @mbggenerated
     */
    private Integer messageeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..message_board.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..message_board.messager_email
     *
     * @mbggenerated
     */
    private String messagerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..message_board.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..message_board.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phoenix_blog..message_board.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..message_board.id
     *
     * @return the value of phoenix_blog..message_board.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..message_board.id
     *
     * @param id the value for phoenix_blog..message_board.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..message_board.messager_id
     *
     * @return the value of phoenix_blog..message_board.messager_id
     *
     * @mbggenerated
     */
    public Integer getMessagerId() {
        return messagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..message_board.messager_id
     *
     * @param messagerId the value for phoenix_blog..message_board.messager_id
     *
     * @mbggenerated
     */
    public void setMessagerId(Integer messagerId) {
        this.messagerId = messagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..message_board.messagee_id
     *
     * @return the value of phoenix_blog..message_board.messagee_id
     *
     * @mbggenerated
     */
    public Integer getMessageeId() {
        return messageeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..message_board.messagee_id
     *
     * @param messageeId the value for phoenix_blog..message_board.messagee_id
     *
     * @mbggenerated
     */
    public void setMessageeId(Integer messageeId) {
        this.messageeId = messageeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..message_board.message
     *
     * @return the value of phoenix_blog..message_board.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..message_board.message
     *
     * @param message the value for phoenix_blog..message_board.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..message_board.messager_email
     *
     * @return the value of phoenix_blog..message_board.messager_email
     *
     * @mbggenerated
     */
    public String getMessagerEmail() {
        return messagerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..message_board.messager_email
     *
     * @param messagerEmail the value for phoenix_blog..message_board.messager_email
     *
     * @mbggenerated
     */
    public void setMessagerEmail(String messagerEmail) {
        this.messagerEmail = messagerEmail == null ? null : messagerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..message_board.create_time
     *
     * @return the value of phoenix_blog..message_board.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..message_board.create_time
     *
     * @param createTime the value for phoenix_blog..message_board.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..message_board.deleted
     *
     * @return the value of phoenix_blog..message_board.deleted
     *
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..message_board.deleted
     *
     * @param deleted the value for phoenix_blog..message_board.deleted
     *
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phoenix_blog..message_board.update_time
     *
     * @return the value of phoenix_blog..message_board.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phoenix_blog..message_board.update_time
     *
     * @param updateTime the value for phoenix_blog..message_board.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}