package com.snow.phoenix.blog.app.dao.mapper.phoenix_blog;

import com.snow.phoenix.blog.app.core.model.phoenix_blog.LiveComment;
import com.snow.phoenix.blog.app.core.model.phoenix_blog.LiveCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live_comment
     *
     * @mbggenerated
     */
    int countByExample(LiveCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live_comment
     *
     * @mbggenerated
     */
    int deleteByExample(LiveCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live_comment
     *
     * @mbggenerated
     */
    int insert(LiveComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live_comment
     *
     * @mbggenerated
     */
    int insertSelective(LiveComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live_comment
     *
     * @mbggenerated
     */
    List<LiveComment> selectByExample(LiveCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live_comment
     *
     * @mbggenerated
     */
    LiveComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live_comment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LiveComment record, @Param("example") LiveCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live_comment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LiveComment record, @Param("example") LiveCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LiveComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LiveComment record);
}