package com.snow.phoenix.blog.app.dao.mapper.phoenix_blog;

import com.snow.phoenix.blog.app.core.model.phoenix_blog.Live;
import com.snow.phoenix.blog.app.core.model.phoenix_blog.LiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live
     *
     * @mbggenerated
     */
    int countByExample(LiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live
     *
     * @mbggenerated
     */
    int deleteByExample(LiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live
     *
     * @mbggenerated
     */
    int insert(Live record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live
     *
     * @mbggenerated
     */
    int insertSelective(Live record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live
     *
     * @mbggenerated
     */
    List<Live> selectByExample(LiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live
     *
     * @mbggenerated
     */
    Live selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Live record, @Param("example") LiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Live record, @Param("example") LiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Live record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..live
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Live record);
}