package com.snow.phoenix.blog.app.dao.mapper.phoenix_blog;

import com.snow.phoenix.blog.app.core.model.phoenix_blog.Others;
import com.snow.phoenix.blog.app.core.model.phoenix_blog.OthersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OthersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..others
     *
     * @mbggenerated
     */
    int countByExample(OthersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..others
     *
     * @mbggenerated
     */
    int deleteByExample(OthersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..others
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..others
     *
     * @mbggenerated
     */
    int insert(Others record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..others
     *
     * @mbggenerated
     */
    int insertSelective(Others record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..others
     *
     * @mbggenerated
     */
    List<Others> selectByExample(OthersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..others
     *
     * @mbggenerated
     */
    Others selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..others
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Others record, @Param("example") OthersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..others
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Others record, @Param("example") OthersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..others
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Others record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phoenix_blog..others
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Others record);
}